
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;
import java.util.ArrayList;
import SymbolTable.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\010\000\002\002\005\000\002\002\004\000\002\002" +
    "\005\000\002\002\004\000\002\003\003\000\002\003\003" +
    "\000\002\004\004\000\002\004\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\014\000\004\004\005\001\002\000\004\002\016\001" +
    "\002\000\010\003\007\004\005\006\010\001\002\000\010" +
    "\003\ufffa\004\ufffa\005\ufffa\001\002\000\012\002\ufffe\003" +
    "\ufffe\004\ufffe\005\ufffe\001\002\000\006\003\ufffd\005\ufffd" +
    "\001\002\000\006\003\014\005\015\001\002\000\010\003" +
    "\ufffc\004\005\005\ufffc\001\002\000\010\003\ufffb\004\ufffb" +
    "\005\ufffb\001\002\000\012\002\uffff\003\uffff\004\uffff\005" +
    "\uffff\001\002\000\012\002\001\003\001\004\001\005\001" +
    "\001\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\014\000\004\002\003\001\001\000\002\001\001\000" +
    "\010\002\005\003\010\004\011\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\002\012\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

	symbolTable = new SymbolTable();

    }


   SymbolTable symbolTable;

   public static void main( String[] args )
   {
      try
	  {
		   FileReader file = new FileReader( args[0] );
		   Scanner scanner = new Lexer( file );
		   Parser parser = new Parser( scanner );
		   parser.parse();
	  }
	  catch( Exception e )
	  {
		   e.printStackTrace();
	  }
   }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // Element ::= STARTTAG Content ENDTAG 
            {
              HTMLElement RESULT =null;
		int startleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int startright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String start = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int contentleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int contentright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		HTMLElement content = (HTMLElement)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int endleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int endright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String end = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
              // 1. semantiÄ?ko pravilo 
              if (!start.equals(end)) {
                 System.out.println( "PoÄ?etni tag " + start + " se ne slaÅ¾e sa zavrÅ¡nim tagom " + end + ". " );
              }
              else {
                 // 2. semantiÄ?ko pravilo
                 if (start.equals("table")) {
                    // provera da li je content lista HTML elemenata ili obiÄ?an tekst
                    if (content.childElements != null) {
                       for (int i = 0; i < content.childElements.size(); i++) {
                          HTMLElement row = content.childElements.get(i);
                          if (!row.name.equals("tr")) {
                             System.out.println( "Tabela treba da sadrÅ¾i iskljuÄ?ivo elemente tipa tr. " );
                          }
                          // 5. semantiÄ?ko pravilo
                          else if (i != 0) {
                             // VeÄ‡ smo proverili treÄ‡im pravilom da tr sadrÅ¾i samo th ili td elemente. 
                             // Vrsta sa indeksom 0 moÅ¾e da sadrÅ¾i th na bilo kojoj poziciji pa nju 
                             // ne proveravamo. Ostale tr vrste mogu da sadrÅ¾e th element iskljuÄ?ivo na 
                             // poziciji 0 (prva kolona tabele). 
                             for (int j = 1; j < row.childElements.size(); j++) {
                                if (row.childElements.get(j).name.equals("th"))
                        		   System.out.println( "Element th moÅ¾e biti samo u prvoj vrsti ili prvoj koloni. " );
                             }
                          }
                       } 
                    }
                    else
                       System.out.println( "Tabela moÅ¾e da sadrÅ¾i iskljuÄ?ivo listu elemenata tipa tr. " );
                 }
                 // 3. semantiÄ?ko pravilo
                 else if (start.equals("tr")) {
                    // provera da li je content lista HTML elemenata ili obiÄ?an tekst
                    if (content.childElements != null) {
                       for (HTMLElement element : content.childElements) {
                          if (!element.name.equals("th") && !element.name.equals("td")) {
                             System.out.println( "Element tr treba da sadrÅ¾i iskljuÄ?ivo elemente tipa th ili td. " );
                          }
                       } 
                    }
                    else
                       System.out.println( "Element tr treba da sadrÅ¾i iskljuÄ?ivo elemente tipa th ili td. " );
                 }
                 // 4. semantiÄ?ko pravilo
                 else if (start.equals("td")) {
                    // provera da li je content lista HTML elemenata ili obiÄ?an tekst
                    if (content.childElements != null) {
                       System.out.println( "Element td treba da sadrÅ¾i iskljuÄ?ivo obiÄ?an tekst. " );
                    }
                 }
                 else if (start.equals("th")) {
                    // provera da li je content lista HTML elemenata ili obiÄ?an tekst
                    if (content.childElements != null) {
                       System.out.println( "Element th treba da sadrÅ¾i iskljuÄ?ivo obiÄ?an tekst. " );
                    }
                 }
              }
              RESULT = content;
              RESULT.name = start;
          
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Element",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= Element EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		HTMLElement start_val = (HTMLElement)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Element ::= STARTTAG Content error 
            {
              HTMLElement RESULT =null;
		int startleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int startright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String start = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int contentleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int contentright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		HTMLElement content = (HTMLElement)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
             System.out.println( "Nedostaje zavrÅ¡ni tag za " + start + ". " );
          
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Element",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Element ::= STARTTAG error 
            {
              HTMLElement RESULT =null;
		int startleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int startright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String start = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
             System.out.println( "Nedostaje sadrÅ¾aj taga " + start + ". " );
          
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Element",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Content ::= TEXT 
            {
              HTMLElement RESULT =null;
		int textleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int textright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String text = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
             RESULT = new HTMLElement(text); 
          
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Content",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Content ::= ElementList 
            {
              HTMLElement RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ArrayList<HTMLElement> list = (ArrayList<HTMLElement>)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
             RESULT = new HTMLElement(list); 
          
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Content",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // ElementList ::= ElementList Element 
            {
              ArrayList<HTMLElement> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<HTMLElement> list = (ArrayList<HTMLElement>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int elementleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int elementright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		HTMLElement element = (HTMLElement)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                   list.add(element);
                   RESULT = list; 
              
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ElementList",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // ElementList ::= Element 
            {
              ArrayList<HTMLElement> RESULT =null;
		int elementleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int elementright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		HTMLElement element = (HTMLElement)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                   RESULT = new ArrayList<HTMLElement>();
                   RESULT.add(element); 
              
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ElementList",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
