
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class MPParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public MPParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public MPParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public MPParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\065\000\002\002\005\000\002\002\004\000\002\002" +
    "\005\000\002\002\004\000\002\002\003\000\002\003\006" +
    "\000\002\003\006\000\002\004\004\000\002\004\004\000" +
    "\002\004\002\000\002\005\006\000\002\005\006\000\002" +
    "\005\005\000\002\005\004\000\002\006\005\000\002\006" +
    "\005\000\002\006\003\000\002\007\003\000\002\007\003" +
    "\000\002\007\003\000\002\007\003\000\002\010\003\000" +
    "\002\010\004\000\002\011\003\000\002\011\006\000\002" +
    "\011\006\000\002\011\005\000\002\011\003\000\002\012" +
    "\006\000\002\012\006\000\002\012\005\000\002\012\004" +
    "\000\002\013\004\000\002\013\003\000\002\014\006\000" +
    "\002\014\006\000\002\014\005\000\002\014\004\000\002" +
    "\015\005\000\002\015\003\000\002\016\005\000\002\016" +
    "\003\000\002\017\005\000\002\017\003\000\002\020\003" +
    "\000\002\020\003\000\002\020\003\000\002\020\003\000" +
    "\002\020\003\000\002\020\003\000\002\021\003\000\002" +
    "\021\003\000\002\021\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\115\000\006\003\005\005\006\001\002\000\004\002" +
    "\117\001\002\000\004\002\ufffd\001\002\000\006\003\007" +
    "\012\011\001\002\000\004\002\ufffe\001\002\000\006\003" +
    "\115\004\116\001\002\000\012\003\ufff8\012\ufff8\014\ufff8" +
    "\021\ufff8\001\002\000\012\003\022\012\011\014\021\021" +
    "\023\001\002\000\016\003\uffe6\012\uffe6\013\uffe6\014\uffe6" +
    "\021\uffe6\022\uffe6\001\002\000\010\003\101\025\100\026" +
    "\102\001\002\000\014\003\075\012\011\013\077\014\055" +
    "\021\023\001\002\000\016\003\uffea\012\uffea\013\uffea\014" +
    "\uffea\021\uffea\022\uffea\001\002\000\012\003\ufffa\012\ufffa" +
    "\014\ufffa\021\ufffa\001\002\000\014\003\uffec\012\uffec\013" +
    "\uffec\014\uffec\021\uffec\001\002\000\012\003\ufff1\020\060" +
    "\025\ufff1\026\ufff1\001\002\000\012\003\ufff9\012\ufff9\014" +
    "\ufff9\021\ufff9\001\002\000\006\003\024\012\025\001\002" +
    "\000\016\003\uffe2\012\uffe2\013\uffe2\014\uffe2\021\uffe2\022" +
    "\uffe2\001\002\000\006\003\027\022\030\001\002\000\010" +
    "\003\uffe0\013\uffe0\022\uffe0\001\002\000\016\003\uffe3\012" +
    "\uffe3\013\uffe3\014\uffe3\021\uffe3\022\uffe3\001\002\000\012" +
    "\003\041\014\036\015\037\016\044\001\002\000\010\003" +
    "\033\013\034\022\030\001\002\000\010\003\uffe1\013\uffe1" +
    "\022\uffe1\001\002\000\016\003\uffe4\012\uffe4\013\uffe4\014" +
    "\uffe4\021\uffe4\022\uffe4\001\002\000\016\003\uffe5\012\uffe5" +
    "\013\uffe5\014\uffe5\021\uffe5\022\uffe5\001\002\000\016\003" +
    "\uffd8\017\uffd8\023\uffd8\024\uffd8\035\uffd8\036\uffd8\001\002" +
    "\000\032\003\uffcf\017\uffcf\023\uffcf\024\uffcf\027\uffcf\030" +
    "\uffcf\031\uffcf\032\uffcf\033\uffcf\034\uffcf\035\uffcf\036\uffcf" +
    "\001\002\000\032\003\uffce\017\uffce\023\uffce\024\uffce\027" +
    "\uffce\030\uffce\031\uffce\032\uffce\033\uffce\034\uffce\035\uffce" +
    "\036\uffce\001\002\000\032\003\uffd6\017\uffd6\023\uffd6\024" +
    "\uffd6\027\072\030\066\031\067\032\070\033\071\034\073" +
    "\035\uffd6\036\uffd6\001\002\000\010\003\uffdc\013\uffdc\022" +
    "\uffdc\001\002\000\010\003\053\023\054\036\047\001\002" +
    "\000\016\003\uffda\017\uffda\023\uffda\024\uffda\035\051\036" +
    "\uffda\001\002\000\010\014\036\015\037\016\044\001\002" +
    "\000\006\017\046\036\047\001\002\000\032\003\uffcd\017" +
    "\uffcd\023\uffcd\024\uffcd\027\uffcd\030\uffcd\031\uffcd\032\uffcd" +
    "\033\uffcd\034\uffcd\035\uffcd\036\uffcd\001\002\000\010\014" +
    "\036\015\037\016\044\001\002\000\016\003\uffdb\017\uffdb" +
    "\023\uffdb\024\uffdb\035\051\036\uffdb\001\002\000\010\014" +
    "\036\015\037\016\044\001\002\000\016\003\uffd9\017\uffd9" +
    "\023\uffd9\024\uffd9\035\uffd9\036\uffd9\001\002\000\010\003" +
    "\uffdd\013\uffdd\022\uffdd\001\002\000\012\003\056\012\011" +
    "\014\055\021\023\001\002\000\004\020\060\001\002\000" +
    "\010\003\uffde\013\uffde\022\uffde\001\002\000\010\003\uffdf" +
    "\013\uffdf\022\uffdf\001\002\000\012\003\061\014\036\015" +
    "\037\016\044\001\002\000\016\003\uffe7\012\uffe7\013\uffe7" +
    "\014\uffe7\021\uffe7\022\uffe7\001\002\000\010\003\064\024" +
    "\063\036\047\001\002\000\016\003\uffe9\012\uffe9\013\uffe9" +
    "\014\uffe9\021\uffe9\022\uffe9\001\002\000\016\003\uffe8\012" +
    "\uffe8\013\uffe8\014\uffe8\021\uffe8\022\uffe8\001\002\000\010" +
    "\014\036\015\037\016\044\001\002\000\010\014\uffd4\015" +
    "\uffd4\016\uffd4\001\002\000\010\014\uffd3\015\uffd3\016\uffd3" +
    "\001\002\000\010\014\uffd2\015\uffd2\016\uffd2\001\002\000" +
    "\010\014\uffd1\015\uffd1\016\uffd1\001\002\000\010\014\uffd5" +
    "\015\uffd5\016\uffd5\001\002\000\010\014\uffd0\015\uffd0\016" +
    "\uffd0\001\002\000\016\003\uffd7\017\uffd7\023\uffd7\024\uffd7" +
    "\035\uffd7\036\uffd7\001\002\000\020\003\ufffb\004\ufffb\012" +
    "\ufffb\013\ufffb\014\ufffb\021\ufffb\022\ufffb\001\002\000\014" +
    "\003\uffeb\012\uffeb\013\uffeb\014\uffeb\021\uffeb\001\002\000" +
    "\020\003\ufffc\004\ufffc\012\ufffc\013\ufffc\014\ufffc\021\ufffc" +
    "\022\ufffc\001\002\000\006\003\114\014\113\001\002\000" +
    "\012\003\ufff4\012\ufff4\014\ufff4\021\ufff4\001\002\000\014" +
    "\003\105\006\103\007\110\010\106\011\107\001\002\000" +
    "\006\003\ufff0\024\ufff0\001\002\000\006\003\112\024\111" +
    "\001\002\000\012\003\ufff5\012\ufff5\014\ufff5\021\ufff5\001" +
    "\002\000\006\003\uffee\024\uffee\001\002\000\006\003\uffed" +
    "\024\uffed\001\002\000\006\003\uffef\024\uffef\001\002\000" +
    "\012\003\ufff7\012\ufff7\014\ufff7\021\ufff7\001\002\000\012" +
    "\003\ufff6\012\ufff6\014\ufff6\021\ufff6\001\002\000\010\003" +
    "\ufff3\025\ufff3\026\ufff3\001\002\000\010\003\ufff2\025\ufff2" +
    "\026\ufff2\001\002\000\004\002\uffff\001\002\000\004\002" +
    "\001\001\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\115\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\003\007\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\004\011\001\001\000\016\003" +
    "\012\005\016\006\013\010\014\011\017\012\015\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\003\012\011" +
    "\075\012\015\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\013\030\014\025" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\015" +
    "\041\016\042\017\034\021\037\001\001\000\004\014\031" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\020\064\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\015\044\016\042\017\034" +
    "\021\037\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\016\047\017\034\021\037\001\001\000\002\001\001" +
    "\000\006\017\051\021\037\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\003\012\011\056\012\015\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\015\061\016\042\017\034\021\037\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\021\073\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\007\103\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$MPParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$MPParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$MPParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



   public int errNo = 0;
   public static void main( String[] args )
   {
      try
	  {
		   FileReader file = new FileReader( args[0] );
		   MPLexer scanner = new MPLexer( file );
		   MPParser parser = new MPParser( scanner );
		   parser.parse();
		   if ( parser.errNo == 0 )
		      System.out.println( "Analiza zavrsena. U kodu nema gresaka." );
		   else
		      System.out.println( "Analiza zavrsena. Broj gresaka: " + parser.errNo );
	  }
	  catch( Exception e )
	  {
		   e.printStackTrace();
	  }
   }
   
   public void syntax_error(Symbol cur_token)
   {
   	  // nema nista?
   }
   
   public void report_error(String message, Object info)
   {
   	   System.out.print( message );
   }
   
   public int getLine()
   {
   	  return (( MPLexer) getScanner()).getLine() + 1;
   }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$MPParser$actions {
  private final MPParser parser;

  /** Constructor */
  CUP$MPParser$actions(MPParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$MPParser$do_action_part00000000(
    int                        CUP$MPParser$act_num,
    java_cup.runtime.lr_parser CUP$MPParser$parser,
    java.util.Stack            CUP$MPParser$stack,
    int                        CUP$MPParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$MPParser$result;

      /* select the action based on the action number */
      switch (CUP$MPParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // Program ::= PROGRAM Block PERIOD 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 1:  Program ::= PROGRAM Block PERIOD" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Program",0, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= Program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		RESULT = start_val;
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$MPParser$parser.done_parsing();
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Program ::= PROGRAM Block error 
            {
              Object RESULT =null;
		 System.out.println( "Nedostaje '.' na kraju programa" ); parser.errNo++; 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Program",0, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Program ::= PROGRAM error 
            {
              Object RESULT =null;
		 System.out.println( "! Greska ! u liniji " + parser.getLine() + ": " + "Telo programa je nekorektno."); parser.errNo++; 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Program",0, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Program ::= error 
            {
              Object RESULT =null;
		 System.out.println( "! Greska ! u liniji " + parser.getLine() + ": " + "Nedostaje kljucna rec 'program' na pocetku."); parser.errNo++; 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Program",0, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Block ::= BEGIN Variables StatementList END 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 2:  Block ::= BEGIN Variables StatementList END " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Block",1, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Block ::= BEGIN Variables StatementList error 
            {
              Object RESULT =null;
		 System.out.println( "! Greska ! u liniji " + parser.getLine() + ": " + "Nezavrsen blok (nedostaje kljucna rec 'end')."); parser.errNo++; 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Block",1, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Variables ::= Variables Declaration 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 3:  Variables ::= Variables Declaration" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Variables",2, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Variables ::= Variables error 
            {
              Object RESULT =null;
		 System.out.println( "! Greska ! u liniji " + parser.getLine() + ": " + "Nedostaje deklaracija za promenjive"); parser.errNo++; 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Variables",2, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Variables ::= 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 4:  Variables ::= ε " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Variables",2, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Declaration ::= NameList COLON Type SEMICOLON 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 5:  Declaration ::= NameList COLON Type SEMICOLON " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Declaration",3, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // Declaration ::= NameList COLON Type error 
            {
              Object RESULT =null;
		 System.out.println( "! Greska ! u liniji " + parser.getLine() + ": " + "Nedostaje ';'."); parser.errNo++; 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Declaration",3, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // Declaration ::= NameList COLON error 
            {
              Object RESULT =null;
		 System.out.println( "! Greska ! u liniji " + parser.getLine() + ": " + "Nedostaje tip promenjive."); parser.errNo++; 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Declaration",3, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // Declaration ::= NameList error 
            {
              Object RESULT =null;
		 System.out.println( "! Greska ! u liniji " + parser.getLine() + ": " + "Nedostaje ',' ili ':'."); parser.errNo++; 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Declaration",3, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // NameList ::= NameList COMMA ID 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 6:  NameList ::= NameList COMMA ID" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("NameList",4, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // NameList ::= NameList COMMA error 
            {
              Object RESULT =null;
		 System.out.println( "! Greska ! u liniji " + parser.getLine() + ": " + "Nevalidan ID promenjive"); parser.errNo++; 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("NameList",4, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // NameList ::= ID 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 7:  NameList ::= ID " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("NameList",4, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // Type ::= INTEGER 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 8:  Type ::= INTEGER" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Type",5, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // Type ::= CHAR 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 9:  Type ::= CHAR" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Type",5, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // Type ::= REAL 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 10: Type ::= REAL" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Type",5, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // Type ::= BOOLEAN 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 11: Type ::= BOOLEAN " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Type",5, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // StatementList ::= Statement 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 12: StatementList ::= Statement" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("StatementList",6, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // StatementList ::= StatementList Statement 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 13: StatementList ::= StatementList Statement  " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("StatementList",6, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // Statement ::= SelectStatement 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 14: Statement ::= SelectStatement" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Statement",7, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // Statement ::= ID ASSIGN Expression SEMICOLON 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 15: Statement ::= ID ASSIGN Expression SEMICOLON" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Statement",7, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // Statement ::= ID ASSIGN Expression error 
            {
              Object RESULT =null;
		 System.out.println( "! Greska ! u liniji " + parser.getLine() + ": " + "Nedostaje ';'"); parser.errNo++; 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Statement",7, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // Statement ::= ID ASSIGN error 
            {
              Object RESULT =null;
		 System.out.println( "! Greska ! u liniji " + parser.getLine() + ": " + "Potreban je izraz sa desne strane ':=' simbola."); parser.errNo++; 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Statement",7, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // Statement ::= Block 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 16: Statement ::= Block " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Statement",7, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // SelectStatement ::= SELECT BEGIN CaseList END 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 17: SelectStatement ::= SELECT BEGIN CaseList END " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("SelectStatement",8, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // SelectStatement ::= SELECT BEGIN CaseList error 
            {
              Object RESULT =null;
		 System.out.println( "! Greska ! u liniji " + parser.getLine() + ": " + "Nezavrsen 'select' izraz (nedostaje kljucna rec 'end')."); parser.errNo++; 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("SelectStatement",8, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // SelectStatement ::= SELECT BEGIN error 
            {
              Object RESULT =null;
		 System.out.println( "! Greska ! u liniji " + parser.getLine() + ": " + "Nevalidan slucaj u 'select' izrazu."); parser.errNo++; 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("SelectStatement",8, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // SelectStatement ::= SELECT error 
            {
              Object RESULT =null;
		 System.out.println( "! Greska ! u liniji " + parser.getLine() + ": " + "Lose zapocet 'select' izraz (nedostaje kljucna rec 'begin')."); parser.errNo++; 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("SelectStatement",8, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // CaseList ::= CaseList Case 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 18: CaseList ::= CaseList Case" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("CaseList",9, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // CaseList ::= Case 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 19: CaseList ::= Case " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("CaseList",9, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // Case ::= CASE Expression THEN Statement 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 20: Case ::= CASE Expression THEN Statement " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Case",10, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // Case ::= CASE Expression THEN error 
            {
              Object RESULT =null;
		 System.out.println( "! Greska ! u liniji " + parser.getLine() + ": " + "Nevalidan izraz sa desne strane slucaja."); parser.errNo++; 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Case",10, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // Case ::= CASE Expression error 
            {
              Object RESULT =null;
		 System.out.println( "! Greska ! u liniji " + parser.getLine() + ": " + "Nedostaje '=>'"); parser.errNo++; 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Case",10, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // Case ::= CASE error 
            {
              Object RESULT =null;
		 System.out.println( "! Greska ! u liniji " + parser.getLine() + ": " + "Nevalidan izraz u slucaju."); parser.errNo++; 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Case",10, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // Expression ::= Expression OR AndExpression 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 21: Expression ::= Expression OR AndExpression" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Expression",11, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // Expression ::= AndExpression 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 22: Expression ::= AndExpression  " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Expression",11, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // AndExpression ::= AndExpression AND RelExpression 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 23: AndExpression ::= AndExpression AND RelExpression" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("AndExpression",12, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // AndExpression ::= RelExpression 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 24: AndExpression ::= RelExpression " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("AndExpression",12, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // RelExpression ::= Term RelOp Term 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 25: RelExpression ::= Term RelOp Term" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("RelExpression",13, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // RelExpression ::= Term 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 26: RelExpression ::= Term " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("RelExpression",13, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // RelOp ::= LESS 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 27: RelOp ::= LESS" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("RelOp",14, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // RelOp ::= LESSEQUAL 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 28: RelOp ::= LESSEQUAL" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("RelOp",14, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // RelOp ::= GREATER 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 29: RelOp ::= GREATER" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("RelOp",14, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // RelOp ::= GREATEREQUAL 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 30: RelOp ::= GREATEREQUAL" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("RelOp",14, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // RelOp ::= EQUAL 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 31: RelOp ::= EQUAL" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("RelOp",14, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // RelOp ::= NOTEQUAL 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 32: RelOp ::= NOTEQUAL" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("RelOp",14, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // Term ::= ID 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 33: Term ::= ID" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Term",15, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // Term ::= CONST 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 34: Term ::= CONST" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Term",15, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // Term ::= LEFTPAR Expression RIGHTPAR 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 35: Term ::= LEFTPAR Expression RIGHTPAR" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Term",15, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$MPParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$MPParser$do_action(
    int                        CUP$MPParser$act_num,
    java_cup.runtime.lr_parser CUP$MPParser$parser,
    java.util.Stack            CUP$MPParser$stack,
    int                        CUP$MPParser$top)
    throws java.lang.Exception
    {
              return CUP$MPParser$do_action_part00000000(
                               CUP$MPParser$act_num,
                               CUP$MPParser$parser,
                               CUP$MPParser$stack,
                               CUP$MPParser$top);
    }
}

}
