
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package pplv;

import java_cup.runtime.*;
import java.io.*;
import java.util.*;
import pplv.SymbolTable.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class MPParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public MPParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public MPParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public MPParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\047\000\002\002\005\000\002\002\004\000\002\003" +
    "\006\000\002\004\004\000\002\004\002\000\002\005\006" +
    "\000\002\014\005\000\002\014\003\000\002\015\003\000" +
    "\002\015\003\000\002\015\003\000\002\015\003\000\002" +
    "\006\003\000\002\006\004\000\002\007\003\000\002\007" +
    "\006\000\002\007\003\000\002\010\006\000\002\011\004" +
    "\000\002\011\003\000\002\012\006\000\002\016\005\000" +
    "\002\016\003\000\002\017\005\000\002\017\003\000\002" +
    "\020\005\000\002\020\003\000\002\013\003\000\002\013" +
    "\003\000\002\013\003\000\002\013\003\000\002\013\003" +
    "\000\002\013\003\000\002\021\003\000\002\021\003\000" +
    "\002\021\003\000\002\021\003\000\002\021\003\000\002" +
    "\021\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\077\000\004\005\005\001\002\000\004\002\101\001" +
    "\002\000\004\012\007\001\002\000\004\004\100\001\002" +
    "\000\010\012\ufffd\014\ufffd\020\ufffd\001\002\000\010\012" +
    "\007\014\017\020\020\001\002\000\006\024\067\025\070" +
    "\001\002\000\014\012\ufff1\013\ufff1\014\ufff1\020\ufff1\021" +
    "\ufff1\001\002\000\012\012\007\013\066\014\060\020\020" +
    "\001\002\000\014\012\ufff3\013\ufff3\014\ufff3\020\ufff3\021" +
    "\ufff3\001\002\000\010\012\ufffe\014\ufffe\020\ufffe\001\002" +
    "\000\012\012\ufff5\013\ufff5\014\ufff5\020\ufff5\001\002\000" +
    "\010\017\062\024\ufffa\025\ufffa\001\002\000\004\012\021" +
    "\001\002\000\004\021\023\001\002\000\006\013\uffee\021" +
    "\uffee\001\002\000\016\014\036\015\034\036\040\037\031" +
    "\040\032\041\033\001\002\000\006\013\026\021\023\001" +
    "\002\000\006\013\uffef\021\uffef\001\002\000\014\012\ufff0" +
    "\013\ufff0\014\ufff0\020\ufff0\021\ufff0\001\002\000\014\016" +
    "\uffeb\022\uffeb\023\uffeb\034\055\035\uffeb\001\002\000\006" +
    "\022\057\035\053\001\002\000\030\016\uffdf\022\uffdf\023" +
    "\uffdf\026\uffdf\027\uffdf\030\uffdf\031\uffdf\032\uffdf\033\uffdf" +
    "\034\uffdf\035\uffdf\001\002\000\030\016\uffde\022\uffde\023" +
    "\uffde\026\uffde\027\uffde\030\uffde\031\uffde\032\uffde\033\uffde" +
    "\034\uffde\035\uffde\001\002\000\030\016\uffdd\022\uffdd\023" +
    "\uffdd\026\uffdd\027\uffdd\030\uffdd\031\uffdd\032\uffdd\033\uffdd" +
    "\034\uffdd\035\uffdd\001\002\000\016\014\036\015\034\036" +
    "\040\037\031\040\032\041\033\001\002\000\030\016\uffe7" +
    "\022\uffe7\023\uffe7\026\047\027\042\030\043\031\045\032" +
    "\044\033\046\034\uffe7\035\uffe7\001\002\000\030\016\uffdc" +
    "\022\uffdc\023\uffdc\026\uffdc\027\uffdc\030\uffdc\031\uffdc\032" +
    "\uffdc\033\uffdc\034\uffdc\035\uffdc\001\002\000\014\016\uffe9" +
    "\022\uffe9\023\uffe9\034\uffe9\035\uffe9\001\002\000\030\016" +
    "\uffe0\022\uffe0\023\uffe0\026\uffe0\027\uffe0\030\uffe0\031\uffe0" +
    "\032\uffe0\033\uffe0\034\uffe0\035\uffe0\001\002\000\016\014" +
    "\036\015\034\036\040\037\031\040\032\041\033\001\002" +
    "\000\016\014\uffe5\015\uffe5\036\uffe5\037\uffe5\040\uffe5\041" +
    "\uffe5\001\002\000\016\014\uffe4\015\uffe4\036\uffe4\037\uffe4" +
    "\040\uffe4\041\uffe4\001\002\000\016\014\uffe2\015\uffe2\036" +
    "\uffe2\037\uffe2\040\uffe2\041\uffe2\001\002\000\016\014\uffe3" +
    "\015\uffe3\036\uffe3\037\uffe3\040\uffe3\041\uffe3\001\002\000" +
    "\016\014\uffe1\015\uffe1\036\uffe1\037\uffe1\040\uffe1\041\uffe1" +
    "\001\002\000\016\014\uffe6\015\uffe6\036\uffe6\037\uffe6\040" +
    "\uffe6\041\uffe6\001\002\000\014\016\uffe8\022\uffe8\023\uffe8" +
    "\034\uffe8\035\uffe8\001\002\000\006\016\052\035\053\001" +
    "\002\000\030\016\uffdb\022\uffdb\023\uffdb\026\uffdb\027\uffdb" +
    "\030\uffdb\031\uffdb\032\uffdb\033\uffdb\034\uffdb\035\uffdb\001" +
    "\002\000\016\014\036\015\034\036\040\037\031\040\032" +
    "\041\033\001\002\000\014\016\uffec\022\uffec\023\uffec\034" +
    "\055\035\uffec\001\002\000\016\014\036\015\034\036\040" +
    "\037\031\040\032\041\033\001\002\000\014\016\uffea\022" +
    "\uffea\023\uffea\034\uffea\035\uffea\001\002\000\010\012\007" +
    "\014\060\020\020\001\002\000\004\017\062\001\002\000" +
    "\006\013\uffed\021\uffed\001\002\000\016\014\036\015\034" +
    "\036\040\037\031\040\032\041\033\001\002\000\006\023" +
    "\064\035\053\001\002\000\014\012\ufff2\013\ufff2\014\ufff2" +
    "\020\ufff2\021\ufff2\001\002\000\012\012\ufff4\013\ufff4\014" +
    "\ufff4\020\ufff4\001\002\000\016\004\uffff\012\uffff\013\uffff" +
    "\014\uffff\020\uffff\021\uffff\001\002\000\004\014\077\001" +
    "\002\000\012\006\071\007\075\010\073\011\074\001\002" +
    "\000\004\023\ufff9\001\002\000\004\023\076\001\002\000" +
    "\004\023\ufff7\001\002\000\004\023\ufff6\001\002\000\004" +
    "\023\ufff8\001\002\000\010\012\ufffc\014\ufffc\020\ufffc\001" +
    "\002\000\006\024\ufffb\025\ufffb\001\002\000\004\002\001" +
    "\001\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\077\000\004\002\003\001\001\000\002\001\001\000" +
    "\004\003\005\001\001\000\002\001\001\000\004\004\007" +
    "\001\001\000\016\003\011\005\014\006\012\007\015\010" +
    "\013\014\010\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\003\011\007\064\010\013\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\011\023\012\021\001\001\000" +
    "\002\001\001\000\012\016\027\017\026\020\036\021\034" +
    "\001\001\000\004\012\024\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\016" +
    "\050\017\026\020\036\021\034\001\001\000\004\013\040" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\021\047\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\017\053\020\036\021\034\001" +
    "\001\000\002\001\001\000\006\020\055\021\034\001\001" +
    "\000\002\001\001\000\010\003\011\007\060\010\013\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\016\062" +
    "\017\026\020\036\021\034\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\015\071\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$MPParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$MPParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$MPParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

    symbolTable = new SymbolTable();

    }


   public int warnNo = 0;
   SymbolTable symbolTable;
   
   public static void main( String[] args )
   {
      try
      {
           FileReader file = new FileReader( args[0] );
           java_cup.runtime.Scanner scanner = new MPLexer( file );
           MPParser parser = new MPParser( scanner );
           parser.parse();
           parser.checkWarnings();
		   if ( parser.warnNo == 0 )
		      System.out.println( "Analiza zavrsena. U kodu nema gresaka." );
		   else
		      System.out.println(" Broj upozorenja: " + parser.warnNo );
      }
      catch( Exception e )
      {
           e.printStackTrace();
      }
   }
   
   public void checkWarnings()
   {
      SymbolNode current = symbolTable.getVariables();
      while ( current != null )
      {
      	Variable var = ( Variable ) current;
      	if ( var.last_def == -1 && var.last_use == -1 )
      	{
      		System.out.println( "Upozorenje: Promenljiva " + var.name + 
      			" je deklarisana, ali se nigde ne koristi." );
      		warnNo++;
      	}
      	else if ( var.last_def > var.last_use )
      	{
      		System.out.println( "Upozorenje: Vrednost dodeljena promeljivoj " +
      		    var.name + " u liniji " + var.last_def + " se nigde ne koristi." );
      		warnNo++;
      	}
      	current = current.next;
     }
   }
   
   public void syntax_error(Symbol cur_token)
   {
       
   }
   
   public void report_error(String message, Object info)
   {
       System.out.print( message );
   }
   
   public int getLine()
   {
       return (( MPLexer) getScanner()).getLine();
   }

    boolean isAssignable(Type lhs, Type rhs)
    {
        if ( lhs == null || rhs == null ) return false;
        if ( lhs.tkind == rhs.tkind ) return true;
        if ( rhs.tkind == Type.INTEGER && lhs.tkind == Type.REAL ) return true;
        if ( rhs.tkind == Type.CHARACTER && lhs.tkind == Type.INTEGER ) return true;
        if ( rhs.tkind == Type.CHARACTER && lhs.tkind == Type.REAL ) return true;
        return false;
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$MPParser$actions {
  private final MPParser parser;

  /** Constructor */
  CUP$MPParser$actions(MPParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$MPParser$do_action_part00000000(
    int                        CUP$MPParser$act_num,
    java_cup.runtime.lr_parser CUP$MPParser$parser,
    java.util.Stack            CUP$MPParser$stack,
    int                        CUP$MPParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$MPParser$result;

      /* select the action based on the action number */
      switch (CUP$MPParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // Program ::= PROGRAM Block PERIOD 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 1:  Program ::= PROGRAM Block PERIOD" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Program",0, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= Program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		RESULT = start_val;
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$MPParser$parser.done_parsing();
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Block ::= BEGIN Variables StatementList END 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 2:  Block ::= BEGIN Variables StatementList END " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Block",1, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Variables ::= Variables Declaration 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 3:  Variables ::= Variables Declaration" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Variables",2, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Variables ::= 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 4:  Variables ::= ε " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Variables",2, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Declaration ::= NameList COLON Type SEMICOLON 
            {
              Object RESULT =null;
		int namesleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left;
		int namesright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).right;
		List<String> names = (List<String>)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		pplv.SymbolTable.Type t = (pplv.SymbolTable.Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		
                System.out.println( "Redukcija 5:  Declaration ::= NameList COLON Type SEMICOLON " );
                for ( String name : names ) {
                    if ( !parser.symbolTable.addVar( name, t ) ) {
                        parser.report_error(
                        "Semanticka greska: Promenljiva " + name +
                        " je vec deklarisana (linija " + parser.getLine() + ")\n", null );
                    }
                }
            
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Declaration",3, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // NameList ::= NameList COMMA ID 
            {
              List<String> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		List<String> list = (List<String>)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$MPParser$stack.peek()).value;
		 
                System.out.println( "Redukcija 6:  NameList ::= NameList COMMA ID" );
                RESULT = list;
                RESULT.add( id.toString() );
            
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("NameList",10, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // NameList ::= ID 
            {
              List<String> RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$MPParser$stack.peek()).value;
		
                System.out.println( "Redukcija 7:  NameList ::= ID " );
                RESULT = new ArrayList<>();
                RESULT.add( id.toString() );
            
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("NameList",10, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Type ::= INTEGER 
            {
              pplv.SymbolTable.Type RESULT =null;
		 
                System.out.println( "Redukcija 8:  Type ::= INTEGER" );  
                RESULT = parser.symbolTable.getType("integer");
                if (RESULT == null) {
                    System.err.println("ERROR: getType(\"integer\") returned null!");
                }
            
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Type",11, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Type ::= CHAR 
            {
              pplv.SymbolTable.Type RESULT =null;
		 
                System.out.println( "Redukcija 9:  Type ::= CHAR" );     
                RESULT = parser.symbolTable.getType("char");
                if (RESULT == null) {
                    System.err.println("ERROR: getType(\"char\") returned null!");
                }
            
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Type",11, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Type ::= REAL 
            {
              pplv.SymbolTable.Type RESULT =null;
		 
                System.out.println( "Redukcija 10: Type ::= REAL" );     
                RESULT = parser.symbolTable.getType("real");
                if (RESULT == null) {
                    System.err.println("ERROR: getType(\"real\") returned null!");
                }
            
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Type",11, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // Type ::= BOOLEAN 
            {
              pplv.SymbolTable.Type RESULT =null;
		 
                System.out.println( "Redukcija 11: Type ::= BOOLEAN " ); 
                RESULT = parser.symbolTable.getType("boolean");
                if (RESULT == null) {
                    System.err.println("ERROR: getType(\"boolean\") returned null!");
                }
            
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Type",11, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // StatementList ::= Statement 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 12: StatementList ::= Statement" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("StatementList",4, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // StatementList ::= StatementList Statement 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 13: StatementList ::= StatementList Statement  " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("StatementList",4, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Statement ::= SelectStatement 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 14: Statement ::= SelectStatement" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Statement",5, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Statement ::= ID ASSIGN Expression SEMICOLON 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).value;
		int exprleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		pplv.SymbolTable.Type expr = (pplv.SymbolTable.Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		
                System.out.println( "Redukcija 15: Statement ::= ID ASSIGN Expression SEMICOLON" );
                String name = id.toString();
                Variable var = parser.symbolTable.getVar( name );

                if ( var == null )
                {
                    parser.report_error(
                      "Semanticka greska: Promenljiva " + name +
                      " nije deklarisana (linija " + parser.getLine() + ")\n", null );
                }
                else
                {
                    Type lhs = var.type;
                    Type rhs = expr;
                    
                    // Debug output
                    System.err.println("DEBUG: Assigning to " + name + 
                                     ", lhs=" + (lhs != null ? lhs.tkind : "null") + 
                                     ", rhs=" + (rhs != null ? rhs.tkind : "null"));

                    if ( !parser.isAssignable( lhs, rhs ) )
                    {
                        parser.report_error(
                          "Semanticka greska: Neodgovarajuci tip u dodeli (linija " +
                          parser.getLine() + ")\n", null );
                    }
                    else
                    {
                        var.last_def = parser.getLine();
                    }
                }
            
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Statement",5, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Statement ::= Block 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 16: Statement ::= Block " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Statement",5, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // SelectStatement ::= SELECT BEGIN CaseList END 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 17: SelectStatement ::= SELECT BEGIN CaseList END " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("SelectStatement",6, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // CaseList ::= CaseList Case 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 18: CaseList ::= CaseList Case" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("CaseList",7, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // CaseList ::= Case 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 19: CaseList ::= Case " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("CaseList",7, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // Case ::= CASE Expression THEN Statement 
            {
              Object RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		pplv.SymbolTable.Type expr = (pplv.SymbolTable.Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		
                System.out.println( "Redukcija 20: Case ::= CASE Expression THEN Statement " );
                if ( expr.tkind != Type.BOOLEAN )
                {
                    parser.report_error(
                      "Semanticka greska: CASE izraz mora biti boolean (linija "
                      + parser.getLine() + ")\n", null );
                }
            
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Case",8, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // Expression ::= Expression OR AndExpression 
            {
              pplv.SymbolTable.Type RESULT =null;
		int leftleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int leftright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		pplv.SymbolTable.Type left = (pplv.SymbolTable.Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		int rightleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).left;
		int rightright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).right;
		pplv.SymbolTable.Type right = (pplv.SymbolTable.Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.peek()).value;
		
                System.out.println( "Redukcija 21: Expression ::= Expression OR AndExpression" );
                if ( left.tkind != Type.BOOLEAN || right.tkind != Type.BOOLEAN )
                    parser.report_error(
                      "Semanticka greska: OR zahteva boolean operande (linija "
                      + parser.getLine() + ")\n", null );
                RESULT = parser.symbolTable.getType("boolean");
            
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Expression",12, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // Expression ::= AndExpression 
            {
              pplv.SymbolTable.Type RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).right;
		pplv.SymbolTable.Type expr = (pplv.SymbolTable.Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.peek()).value;
		
                System.out.println( "Redukcija 22: Expression ::= AndExpression  " );
                RESULT = expr;
            
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Expression",12, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // AndExpression ::= AndExpression AND RelExpression 
            {
              pplv.SymbolTable.Type RESULT =null;
		int leftleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int leftright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		pplv.SymbolTable.Type left = (pplv.SymbolTable.Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		int rightleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).left;
		int rightright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).right;
		pplv.SymbolTable.Type right = (pplv.SymbolTable.Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.peek()).value;
		 
                System.out.println( "Redukcija 23: AndExpression ::= AndExpression AND RelExpression" );
                if ( left.tkind != Type.BOOLEAN || right.tkind != Type.BOOLEAN )
                    parser.report_error(
                      "Semanticka greska: AND zahteva boolean operande (linija "
                      + parser.getLine() + ")\n", null );
                RESULT = parser.symbolTable.getType("boolean");
            
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("AndExpression",13, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // AndExpression ::= RelExpression 
            {
              pplv.SymbolTable.Type RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).right;
		pplv.SymbolTable.Type expr = (pplv.SymbolTable.Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.peek()).value;
		 
                System.out.println( "Redukcija 24: AndExpression ::= RelExpression " );
                RESULT = expr;
            
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("AndExpression",13, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // RelExpression ::= Term RelOp Term 
            {
              pplv.SymbolTable.Type RESULT =null;
		int leftleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int leftright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		pplv.SymbolTable.Type left = (pplv.SymbolTable.Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		int rightleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).left;
		int rightright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).right;
		pplv.SymbolTable.Type right = (pplv.SymbolTable.Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.peek()).value;
		
                System.out.println( "Redukcija 25: RelExpression ::= Term RelOp Term" );
                if ( left.tkind > Type.REAL || right.tkind > Type.REAL )
                {
                    parser.report_error(
                      "Semanticka greska: Relacioni operator nad nenumerickim tipom (linija "
                      + parser.getLine() + ")\n", null );
                }
                RESULT = parser.symbolTable.getType("boolean");
            
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("RelExpression",14, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // RelExpression ::= Term 
            {
              pplv.SymbolTable.Type RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).right;
		pplv.SymbolTable.Type t = (pplv.SymbolTable.Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.peek()).value;
		
                System.out.println( "Redukcija 26: RelExpression ::= Term " );
                RESULT = t;
            
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("RelExpression",14, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // RelOp ::= LESS 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 27: RelOp ::= LESS" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("RelOp",9, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // RelOp ::= LESSEQUAL 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 28: RelOp ::= LESSEQUAL" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("RelOp",9, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // RelOp ::= GREATER 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 29: RelOp ::= GREATER" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("RelOp",9, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // RelOp ::= GREATEREQUAL 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 30: RelOp ::= GREATEREQUAL" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("RelOp",9, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // RelOp ::= EQUAL 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 31: RelOp ::= EQUAL" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("RelOp",9, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // RelOp ::= NOTEQUAL 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 32: RelOp ::= NOTEQUAL" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("RelOp",9, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // Term ::= INTCONST 
            {
              pplv.SymbolTable.Type RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).right;
		Integer c = (Integer)((java_cup.runtime.Symbol) CUP$MPParser$stack.peek()).value;
		
                System.out.println( "Redukcija 33: Term ::= INTCONST" );
                RESULT = parser.symbolTable.getType("integer");
                if (RESULT == null) System.err.println("ERROR: Term INTCONST - getType returned null");
            
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Term",15, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // Term ::= REALCONST 
            {
              pplv.SymbolTable.Type RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).right;
		Double c = (Double)((java_cup.runtime.Symbol) CUP$MPParser$stack.peek()).value;
		
                System.out.println( "Redukcija 34: Term ::= REALCONST" );
                RESULT = parser.symbolTable.getType("real");
                if (RESULT == null) System.err.println("ERROR: Term REALCONST - getType returned null");
            
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Term",15, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // Term ::= CHARCONST 
            {
              pplv.SymbolTable.Type RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).right;
		Character c = (Character)((java_cup.runtime.Symbol) CUP$MPParser$stack.peek()).value;
		
                System.out.println( "Redukcija 35: Term ::= CHARCONST" );
                RESULT = parser.symbolTable.getType("char");
                if (RESULT == null) {
                    RESULT = parser.symbolTable.getType("character");
                    if (RESULT == null) System.err.println("ERROR: Term CHARCONST - getType returned null");
                }
            
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Term",15, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // Term ::= BOOLCONST 
            {
              pplv.SymbolTable.Type RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).right;
		Boolean c = (Boolean)((java_cup.runtime.Symbol) CUP$MPParser$stack.peek()).value;
		
                System.out.println( "Redukcija 36: Term ::= BOOLCONST" );
                RESULT = parser.symbolTable.getType("boolean");
                if (RESULT == null) {
                    RESULT = parser.symbolTable.getType("boolean");
                    if (RESULT == null) System.err.println("ERROR: Term BOOLCONST - getType returned null");
                }
            
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Term",15, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // Term ::= ID 
            {
              pplv.SymbolTable.Type RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$MPParser$stack.peek()).value;
		
                System.out.println( "Redukcija 37: Term ::= ID" );
                String name = id.toString();
                Variable var = parser.symbolTable.getVar(name);

                if (var == null)
                {
                    parser.report_error("Semanticka greska: Promenljiva " + name +
                         " nije deklarisana (linija " + parser.getLine() + ")\n", null);
                    // Try to get unknown type, if it doesn't exist, use integer as fallback
                    Type unknownType = parser.symbolTable.getType("unknown");
                    RESULT = (unknownType != null) ? unknownType : parser.symbolTable.getType("integer");
                }
                else
                {
                    if (var.last_def == -1)
                        parser.report_error("Semanticka greska: Promenljiva " + name +
                          " se koristi pre inicijalizacije (linija " + parser.getLine() + ")\n", null);

                    var.last_use = parser.getLine();
                    RESULT = var.type;
                }
            
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Term",15, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // Term ::= LEFTPAR Expression RIGHTPAR 
            {
              pplv.SymbolTable.Type RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		pplv.SymbolTable.Type expr = (pplv.SymbolTable.Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		
                System.out.println( "Redukcija 38: Term ::= LEFTPAR Expression RIGHTPAR" );
                RESULT = expr;
            
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Term",15, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$MPParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$MPParser$do_action(
    int                        CUP$MPParser$act_num,
    java_cup.runtime.lr_parser CUP$MPParser$parser,
    java.util.Stack            CUP$MPParser$stack,
    int                        CUP$MPParser$top)
    throws java.lang.Exception
    {
              return CUP$MPParser$do_action_part00000000(
                               CUP$MPParser$act_num,
                               CUP$MPParser$parser,
                               CUP$MPParser$stack,
                               CUP$MPParser$top);
    }
}

}
