
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package pplv;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 26;
  public static final int SEMICOLON = 17;
  public static final int SELECT = 14;
  public static final int OR = 27;
  public static final int EQUAL = 24;
  public static final int THEN = 16;
  public static final int NOTEQUAL = 25;
  public static final int CHAR = 5;
  public static final int LEFTPAR = 11;
  public static final int END = 9;
  public static final int PERIOD = 2;
  public static final int GREATER = 22;
  public static final int INTCONST = 28;
  public static final int RIGHTPAR = 12;
  public static final int LESSEQUAL = 21;
  public static final int COLON = 19;
  public static final int ID = 10;
  public static final int PROGRAM = 3;
  public static final int BEGIN = 8;
  public static final int BOOLEAN = 7;
  public static final int COMMA = 18;
  public static final int EOF = 0;
  public static final int CHARCONST = 30;
  public static final int REALCONST = 29;
  public static final int CASE = 15;
  public static final int error = 1;
  public static final int ASSIGN = 13;
  public static final int INTEGER = 4;
  public static final int REAL = 6;
  public static final int GREATEREQUAL = 23;
  public static final int BOOLCONST = 31;
  public static final int LESS = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PERIOD",
  "PROGRAM",
  "INTEGER",
  "CHAR",
  "REAL",
  "BOOLEAN",
  "BEGIN",
  "END",
  "ID",
  "LEFTPAR",
  "RIGHTPAR",
  "ASSIGN",
  "SELECT",
  "CASE",
  "THEN",
  "SEMICOLON",
  "COMMA",
  "COLON",
  "LESS",
  "LESSEQUAL",
  "GREATER",
  "GREATEREQUAL",
  "EQUAL",
  "NOTEQUAL",
  "AND",
  "OR",
  "INTCONST",
  "REALCONST",
  "CHARCONST",
  "BOOLCONST"
  };
}

