
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class MPParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public MPParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public MPParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public MPParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\044\000\002\002\005\000\002\002\004\000\002\003" +
    "\006\000\002\004\004\000\002\004\002\000\002\005\006" +
    "\000\002\006\005\000\002\006\003\000\002\007\003\000" +
    "\002\007\003\000\002\007\003\000\002\007\003\000\002" +
    "\010\003\000\002\010\004\000\002\011\003\000\002\011" +
    "\006\000\002\011\003\000\002\012\006\000\002\013\004" +
    "\000\002\013\003\000\002\014\006\000\002\015\005\000" +
    "\002\015\003\000\002\016\005\000\002\016\003\000\002" +
    "\017\005\000\002\017\003\000\002\020\003\000\002\020" +
    "\003\000\002\020\003\000\002\020\003\000\002\020\003" +
    "\000\002\020\003\000\002\021\003\000\002\021\003\000" +
    "\002\021\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\074\000\004\005\005\001\002\000\004\002\076\001" +
    "\002\000\004\012\007\001\002\000\004\004\075\001\002" +
    "\000\010\012\ufffd\014\ufffd\021\ufffd\001\002\000\010\012" +
    "\007\014\017\021\020\001\002\000\006\025\064\026\065" +
    "\001\002\000\014\012\ufff1\013\ufff1\014\ufff1\021\ufff1\022" +
    "\ufff1\001\002\000\012\012\007\013\063\014\045\021\020" +
    "\001\002\000\014\012\ufff3\013\ufff3\014\ufff3\021\ufff3\022" +
    "\ufff3\001\002\000\010\012\ufffe\014\ufffe\021\ufffe\001\002" +
    "\000\012\012\ufff5\013\ufff5\014\ufff5\021\ufff5\001\002\000" +
    "\010\020\047\025\ufffa\026\ufffa\001\002\000\004\012\021" +
    "\001\002\000\004\022\023\001\002\000\006\013\uffee\022" +
    "\uffee\001\002\000\010\014\030\015\031\016\035\001\002" +
    "\000\006\013\026\022\023\001\002\000\006\013\uffef\022" +
    "\uffef\001\002\000\014\012\ufff0\013\ufff0\014\ufff0\021\ufff0" +
    "\022\ufff0\001\002\000\014\017\uffe9\023\uffe9\024\uffe9\035" +
    "\uffe9\036\uffe9\001\002\000\030\017\uffe0\023\uffe0\024\uffe0" +
    "\027\uffe0\030\uffe0\031\uffe0\032\uffe0\033\uffe0\034\uffe0\035" +
    "\uffe0\036\uffe0\001\002\000\030\017\uffdf\023\uffdf\024\uffdf" +
    "\027\uffdf\030\uffdf\031\uffdf\032\uffdf\033\uffdf\034\uffdf\035" +
    "\uffdf\036\uffdf\001\002\000\030\017\uffe7\023\uffe7\024\uffe7" +
    "\027\060\030\053\031\054\032\056\033\055\034\057\035" +
    "\uffe7\036\uffe7\001\002\000\006\023\044\036\040\001\002" +
    "\000\014\017\uffeb\023\uffeb\024\uffeb\035\042\036\uffeb\001" +
    "\002\000\010\014\030\015\031\016\035\001\002\000\006" +
    "\017\037\036\040\001\002\000\030\017\uffde\023\uffde\024" +
    "\uffde\027\uffde\030\uffde\031\uffde\032\uffde\033\uffde\034\uffde" +
    "\035\uffde\036\uffde\001\002\000\010\014\030\015\031\016" +
    "\035\001\002\000\014\017\uffec\023\uffec\024\uffec\035\042" +
    "\036\uffec\001\002\000\010\014\030\015\031\016\035\001" +
    "\002\000\014\017\uffea\023\uffea\024\uffea\035\uffea\036\uffea" +
    "\001\002\000\010\012\007\014\045\021\020\001\002\000" +
    "\004\020\047\001\002\000\006\013\uffed\022\uffed\001\002" +
    "\000\010\014\030\015\031\016\035\001\002\000\006\024" +
    "\051\036\040\001\002\000\014\012\ufff2\013\ufff2\014\ufff2" +
    "\021\ufff2\022\ufff2\001\002\000\010\014\030\015\031\016" +
    "\035\001\002\000\010\014\uffe5\015\uffe5\016\uffe5\001\002" +
    "\000\010\014\uffe4\015\uffe4\016\uffe4\001\002\000\010\014" +
    "\uffe2\015\uffe2\016\uffe2\001\002\000\010\014\uffe3\015\uffe3" +
    "\016\uffe3\001\002\000\010\014\uffe1\015\uffe1\016\uffe1\001" +
    "\002\000\010\014\uffe6\015\uffe6\016\uffe6\001\002\000\014" +
    "\017\uffe8\023\uffe8\024\uffe8\035\uffe8\036\uffe8\001\002\000" +
    "\012\012\ufff4\013\ufff4\014\ufff4\021\ufff4\001\002\000\016" +
    "\004\uffff\012\uffff\013\uffff\014\uffff\021\uffff\022\uffff\001" +
    "\002\000\004\014\074\001\002\000\012\006\066\007\072" +
    "\010\070\011\071\001\002\000\004\024\ufff9\001\002\000" +
    "\004\024\073\001\002\000\004\024\ufff7\001\002\000\004" +
    "\024\ufff6\001\002\000\004\024\ufff8\001\002\000\010\012" +
    "\ufffc\014\ufffc\021\ufffc\001\002\000\006\025\ufffb\026\ufffb" +
    "\001\002\000\004\002\001\001\002\000\004\002\000\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\074\000\004\002\003\001\001\000\002\001\001\000" +
    "\004\003\005\001\001\000\002\001\001\000\004\004\007" +
    "\001\001\000\016\003\011\005\014\006\010\010\012\011" +
    "\015\012\013\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\003\011\011\061\012\013\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\013\023\014\021\001\001\000" +
    "\002\001\001\000\012\015\032\016\033\017\026\021\031" +
    "\001\001\000\004\014\024\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\020\051\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\015\035\016\033\017\026\021\031" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\016" +
    "\040\017\026\021\031\001\001\000\002\001\001\000\006" +
    "\017\042\021\031\001\001\000\002\001\001\000\010\003" +
    "\011\011\045\012\013\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\015\047\016\033\017\026\021\031\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\021\060" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\007\066\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$MPParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$MPParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$MPParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



   public static void main( String[] args )
   {
      try
	  {
		   FileReader file = new FileReader( args[0] );
		   Scanner scanner = new MPLexer( file );
		   MPParser parser = new MPParser( scanner );
		   parser.parse();
	  }
	  catch( Exception e )
	  {
		   e.printStackTrace();
	  }
   }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$MPParser$actions {
  private final MPParser parser;

  /** Constructor */
  CUP$MPParser$actions(MPParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$MPParser$do_action_part00000000(
    int                        CUP$MPParser$act_num,
    java_cup.runtime.lr_parser CUP$MPParser$parser,
    java.util.Stack            CUP$MPParser$stack,
    int                        CUP$MPParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$MPParser$result;

      /* select the action based on the action number */
      switch (CUP$MPParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // Program ::= PROGRAM Block PERIOD 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 1:  Program ::= PROGRAM Block PERIOD" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Program",0, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= Program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		RESULT = start_val;
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$MPParser$parser.done_parsing();
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Block ::= BEGIN Variables StatementList END 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 2:  Block ::= BEGIN Variables StatementList END " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Block",1, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Variables ::= Variables Declaration 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 3:  Variables ::= Variables Declaration" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Variables",2, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Variables ::= 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 4:  Variables ::= ε " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Variables",2, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Declaration ::= NameList COLON Type SEMICOLON 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 5:  Declaration ::= NameList COLON Type SEMICOLON " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Declaration",3, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // NameList ::= NameList COMMA ID 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 6:  NameList ::= NameList COMMA ID" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("NameList",4, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // NameList ::= ID 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 7:  NameList ::= ID " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("NameList",4, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Type ::= INTEGER 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 8:  Type ::= INTEGER" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Type",5, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Type ::= CHAR 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 9:  Type ::= CHAR" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Type",5, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Type ::= REAL 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 10: Type ::= REAL" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Type",5, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // Type ::= BOOLEAN 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 11: Type ::= BOOLEAN " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Type",5, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // StatementList ::= Statement 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 12: StatementList ::= Statement" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("StatementList",6, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // StatementList ::= StatementList Statement 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 13: StatementList ::= StatementList Statement  " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("StatementList",6, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Statement ::= SelectStatement 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 14: Statement ::= SelectStatement" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Statement",7, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Statement ::= ID ASSIGN Expression SEMICOLON 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 15: Statement ::= ID ASSIGN Expression SEMICOLON" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Statement",7, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Statement ::= Block 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 16: Statement ::= Block " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Statement",7, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // SelectStatement ::= SELECT BEGIN CaseList END 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 17: SelectStatement ::= SELECT BEGIN CaseList END " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("SelectStatement",8, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // CaseList ::= CaseList Case 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 18: CaseList ::= CaseList Case" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("CaseList",9, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // CaseList ::= Case 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 19: CaseList ::= Case " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("CaseList",9, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // Case ::= CASE Expression THEN Statement 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 20: Case ::= CASE Expression THEN Statement " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Case",10, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // Expression ::= Expression OR AndExpression 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 21: Expression ::= Expression OR AndExpression" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Expression",11, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // Expression ::= AndExpression 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 22: Expression ::= AndExpression  " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Expression",11, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // AndExpression ::= AndExpression AND RelExpression 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 23: AndExpression ::= AndExpression AND RelExpression" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("AndExpression",12, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // AndExpression ::= RelExpression 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 24: AndExpression ::= RelExpression " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("AndExpression",12, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // RelExpression ::= Term RelOp Term 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 25: RelExpression ::= Term RelOp Term" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("RelExpression",13, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // RelExpression ::= Term 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 26: RelExpression ::= Term " ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("RelExpression",13, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // RelOp ::= LESS 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 27: RelOp ::= LESS" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("RelOp",14, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // RelOp ::= LESSEQUAL 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 28: RelOp ::= LESSEQUAL" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("RelOp",14, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // RelOp ::= GREATER 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 29: RelOp ::= GREATER" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("RelOp",14, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // RelOp ::= GREATEREQUAL 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 30: RelOp ::= GREATEREQUAL" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("RelOp",14, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // RelOp ::= EQUAL 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 31: RelOp ::= EQUAL" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("RelOp",14, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // RelOp ::= NOTEQUAL 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 32: RelOp ::= NOTEQUAL" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("RelOp",14, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // Term ::= ID 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 33: Term ::= ID" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Term",15, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // Term ::= CONST 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 34: Term ::= CONST" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Term",15, ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // Term ::= LEFTPAR Expression RIGHTPAR 
            {
              Object RESULT =null;
		 System.out.println( "Redukcija 35: Term ::= LEFTPAR Expression RIGHTPAR" ); 
              CUP$MPParser$result = parser.getSymbolFactory().newSymbol("Term",15, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)), ((java_cup.runtime.Symbol)CUP$MPParser$stack.peek()), RESULT);
            }
          return CUP$MPParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$MPParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$MPParser$do_action(
    int                        CUP$MPParser$act_num,
    java_cup.runtime.lr_parser CUP$MPParser$parser,
    java.util.Stack            CUP$MPParser$stack,
    int                        CUP$MPParser$top)
    throws java.lang.Exception
    {
              return CUP$MPParser$do_action_part00000000(
                               CUP$MPParser$act_num,
                               CUP$MPParser$parser,
                               CUP$MPParser$stack,
                               CUP$MPParser$top);
    }
}

}
