
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 27;
  public static final int SEMICOLON = 18;
  public static final int SELECT = 15;
  public static final int OR = 28;
  public static final int EQUAL = 25;
  public static final int THEN = 17;
  public static final int NOTEQUAL = 26;
  public static final int CHAR = 5;
  public static final int LEFTPAR = 12;
  public static final int END = 9;
  public static final int PERIOD = 2;
  public static final int GREATER = 23;
  public static final int RIGHTPAR = 13;
  public static final int LESSEQUAL = 22;
  public static final int COLON = 20;
  public static final int ID = 10;
  public static final int PROGRAM = 3;
  public static final int BEGIN = 8;
  public static final int BOOLEAN = 7;
  public static final int COMMA = 19;
  public static final int EOF = 0;
  public static final int CONST = 11;
  public static final int CASE = 16;
  public static final int error = 1;
  public static final int ASSIGN = 14;
  public static final int INTEGER = 4;
  public static final int REAL = 6;
  public static final int GREATEREQUAL = 24;
  public static final int LESS = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PERIOD",
  "PROGRAM",
  "INTEGER",
  "CHAR",
  "REAL",
  "BOOLEAN",
  "BEGIN",
  "END",
  "ID",
  "CONST",
  "LEFTPAR",
  "RIGHTPAR",
  "ASSIGN",
  "SELECT",
  "CASE",
  "THEN",
  "SEMICOLON",
  "COMMA",
  "COLON",
  "LESS",
  "LESSEQUAL",
  "GREATER",
  "GREATEREQUAL",
  "EQUAL",
  "NOTEQUAL",
  "AND",
  "OR"
  };
}

