
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;
import java.util.ArrayList;
import SymbolTable.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\024\000\002\002\011\000\002\002\004\000\002\002" +
    "\011\000\002\002\010\000\002\002\007\000\002\002\006" +
    "\000\002\002\005\000\002\002\004\000\002\002\003\000" +
    "\002\003\003\000\002\003\003\000\002\004\003\000\002" +
    "\004\005\000\002\004\005\000\002\004\004\000\002\005" +
    "\005\000\002\005\005\000\002\005\004\000\002\006\003" +
    "\000\002\006\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\036\000\006\003\006\005\005\001\002\000\004\002" +
    "\040\001\002\000\006\003\010\004\007\001\002\000\004" +
    "\002\ufff9\001\002\000\006\003\012\006\011\001\002\000" +
    "\004\002\ufffa\001\002\000\010\003\015\011\016\012\013" +
    "\001\002\000\004\002\ufffb\001\002\000\006\003\ufff7\007" +
    "\ufff7\001\002\000\006\003\017\007\020\001\002\000\004" +
    "\002\ufffc\001\002\000\006\003\ufff8\007\ufff8\001\002\000" +
    "\004\002\ufffd\001\002\000\006\003\023\004\021\001\002" +
    "\000\006\003\033\006\032\001\002\000\010\003\ufff6\010" +
    "\ufff6\013\ufff6\001\002\000\004\002\ufffe\001\002\000\010" +
    "\003\025\010\026\013\027\001\002\000\012\002\uffff\003" +
    "\ufff3\010\ufff3\013\ufff3\001\002\000\004\002\001\001\002" +
    "\000\006\003\031\004\021\001\002\000\010\003\ufff5\010" +
    "\ufff5\013\ufff5\001\002\000\010\003\ufff4\010\ufff4\013\ufff4" +
    "\001\002\000\010\003\035\014\037\015\034\001\002\000" +
    "\010\003\ufff0\010\ufff0\013\ufff0\001\002\000\010\003\uffee" +
    "\010\uffee\013\uffee\001\002\000\010\003\ufff1\010\ufff1\013" +
    "\ufff1\001\002\000\010\003\ufff2\010\ufff2\013\ufff2\001\002" +
    "\000\010\003\uffef\010\uffef\013\uffef\001\002\000\004\002" +
    "\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\036\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\003\013\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\004\023\005\021\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\005\027\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\006\035\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

	symbolTable = new SymbolTable();

    }


   SymbolTable symbolTable;

   public static void main( String[] args )
   {
      try
	  {
		   FileReader file = new FileReader( args[0] );
		   Scanner scanner = new Lexer( file );
		   Parser parser = new Parser( scanner );
		   parser.parse();
	  }
	  catch( Exception e )
	  {
		   e.printStackTrace();
	  }
   }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // EnumType ::= ENUM ID DVE_TACKE Type LEVA_ZAGRADA ConstantList DESNA_ZAGRADA 
            {
              Object RESULT =null;
		int imeEnumaleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int imeEnumaright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		String imeEnuma = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int tipleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int tipright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Type tip = (Type)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int listaleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int listaright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<KonstantaSaImenom> lista = (ArrayList<KonstantaSaImenom>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
              if (parser.symbolTable.getType( imeEnuma ) != null) {
                 System.out.println( "Tip sa nazivom " + imeEnuma + " veÄ‡ postoji. " );
              }
              for (KonstantaSaImenom element : lista) {
                 if (element.konstanta.type.tkind != tip.tkind) {
                    System.out.println("Tip elementa enumeracije " + element.ime 
                    + " se razlikuje od tipa enumeracije " + tip.name);
                 }
              }
           
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EnumType",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= EnumType EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // EnumType ::= ENUM ID DVE_TACKE Type LEVA_ZAGRADA ConstantList error 
            {
              Object RESULT =null;
		
              System.out.println( "Nedostaje desna zagrada." );
           
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EnumType",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // EnumType ::= ENUM ID DVE_TACKE Type LEVA_ZAGRADA error 
            {
              Object RESULT =null;
		
              System.out.println( "Nedostaje lista konstanti." );
           
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EnumType",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // EnumType ::= ENUM ID DVE_TACKE Type error 
            {
              Object RESULT =null;
		
              System.out.println( "Nedostaje leva zagrada." );
           
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EnumType",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // EnumType ::= ENUM ID DVE_TACKE error 
            {
              Object RESULT =null;
		
              System.out.println( "Nedostaje tip podataka." );
           
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EnumType",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // EnumType ::= ENUM ID error 
            {
              Object RESULT =null;
		
              System.out.println( "Nedostaje simbol :." );
           
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EnumType",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // EnumType ::= ENUM error 
            {
              Object RESULT =null;
		
              System.out.println( "Nedostaje naziv enumeracije." );
           
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EnumType",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // EnumType ::= error 
            {
              Object RESULT =null;
		
              System.out.println( "Nedostaje cela definicija enumeracije." );
           
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EnumType",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Type ::= INT 
            {
              Type RESULT =null;
		
          RESULT = parser.symbolTable.getType( "integer" );
          // Da ne bismo menjali implementaciju klase SymbolTable umesto tipa podataka 
          // "int" koristimo postojeÄ‡i tip podataka "integer"
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Type",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Type ::= STRING 
            {
              Type RESULT =null;
		
          RESULT = parser.symbolTable.getType( "char" );
          // Da ne bismo menjali implementaciju klase SymbolTable umesto tipa podataka 
          // "string" koristimo postojeÄ‡i tip podataka "char"
       
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Type",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // ConstantList ::= ConstantDefinition 
            {
              ArrayList<KonstantaSaImenom> RESULT =null;
		int cdleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cdright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		KonstantaSaImenom cd = (KonstantaSaImenom)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                  RESULT = new ArrayList<KonstantaSaImenom>();
                  RESULT.add(cd); 
               
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ConstantList",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // ConstantList ::= ConstantList ZAREZ ConstantDefinition 
            {
              ArrayList<KonstantaSaImenom> RESULT =null;
		int listaleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int listaright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ArrayList<KonstantaSaImenom> lista = (ArrayList<KonstantaSaImenom>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int cdleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cdright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		KonstantaSaImenom cd = (KonstantaSaImenom)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                  for (KonstantaSaImenom postojecaKonstanta : lista) {
                     if (postojecaKonstanta.ime.equals(cd.ime)) {
                        System.out.println("SimboliÄ?ko ime " + cd.ime 
                           + " se ponavlja u enumeraciji. ");
                     }
                     if (postojecaKonstanta.konstanta.value.equals(cd.konstanta.value)) {
                        System.out.println("Vrednost konstante " + cd.konstanta.value 
                           + " se ponavlja u enumeraciji. ");
                     }
                  } 
                  lista.add(cd);
                  RESULT = lista; 
               
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ConstantList",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // ConstantList ::= ConstantList ZAREZ error 
            {
              ArrayList<KonstantaSaImenom> RESULT =null;
		
                  System.out.println( "Nedostaje definicija konstante posle zareza." );
               
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ConstantList",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // ConstantList ::= ConstantList error 
            {
              ArrayList<KonstantaSaImenom> RESULT =null;
		
                  System.out.println( "Nedostaje zarez u listi konstanti." );
               
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ConstantList",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // ConstantDefinition ::= ID DVE_TACKE Konstanta 
            {
              KonstantaSaImenom RESULT =null;
		int imeleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int imeright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String ime = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int konstantaleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int konstantaright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Constant konstanta = (Constant)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                        RESULT = new KonstantaSaImenom(ime, konstanta);
                     
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ConstantDefinition",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // ConstantDefinition ::= ID DVE_TACKE error 
            {
              KonstantaSaImenom RESULT =null;
		
                        System.out.println( "Nedostaje konstanta posle dve taÄ?ke." );
                     
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ConstantDefinition",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // ConstantDefinition ::= ID error 
            {
              KonstantaSaImenom RESULT =null;
		
                        System.out.println( "Nedostaju dve taÄ?ke posle identifikatora." );
                     
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ConstantDefinition",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // Konstanta ::= INT_CONST 
            {
              Constant RESULT =null;
		int vrednostleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vrednostright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object vrednost = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
              RESULT = new Constant( parser.symbolTable.getType( "integer" ), vrednost );
              // Da ne bismo menjali implementaciju klase SymbolTable umesto tipa podataka 
              // "int" koristimo postojeÄ‡i tip podataka "integer"
           
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Konstanta",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // Konstanta ::= STRING_CONST 
            {
              Constant RESULT =null;
		int vrednostleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vrednostright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object vrednost = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
              RESULT = new Constant( parser.symbolTable.getType( "char" ), vrednost );
              // Da ne bismo menjali implementaciju klase SymbolTable umesto tipa podataka 
              // "string" koristimo postojeÄ‡i tip podataka "char"
           
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Konstanta",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
