
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ENUM = 3;
  public static final int INT = 7;
  public static final int ZAREZ = 9;
  public static final int INT_CONST = 10;
  public static final int DESNA_ZAGRADA = 6;
  public static final int STRING_CONST = 11;
  public static final int LEVA_ZAGRADA = 5;
  public static final int STRING = 8;
  public static final int EOF = 0;
  public static final int ID = 2;
  public static final int error = 1;
  public static final int DVE_TACKE = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "ENUM",
  "DVE_TACKE",
  "LEVA_ZAGRADA",
  "DESNA_ZAGRADA",
  "INT",
  "STRING",
  "ZAREZ",
  "INT_CONST",
  "STRING_CONST"
  };
}

